export enum ROLES {
    ADMIN_ROLE = "ADMIN_ROLE",
    USER_ROLE = "USER_ROLE"
}

export enum DB_RESTRICTION {
    CASCADE = "CASCADE",
    RESTRICT = "RESTRICT",
    NO_ACTION = "NO ACTION",
    SET_NULL = "SET NULL",
    SET_DEFAULT = "SET DEFAULT"
}